version: '3'
services:
  web:
    build: .
    working_dir: /usr/src/app/webapp
    command: gunicorn --workers 3 webapp.asgi:application -k uvicorn.workers.UvicornWorker -b :8000
    hostname: webs
    environment:
      - DJANGO_SETTINGS_MODULE=webapp.settings
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - web
      - storage
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres
    hostname: dbs
    networks:
      - storage
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  gateway:
    image: nginx:latest
    hostname: facade
    networks:
      - web
    ports:
      - '8000:8000'  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
networks:
  web:
  storage: